// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW16KCmgWhL9xXjxFpfIl61D4-ia2Lwcs',
    appId: '1:902733428361:web:1bf7d4afc5a708c08ab858',
    messagingSenderId: '902733428361',
    projectId: 'simpleca-925ab',
    authDomain: 'simpleca-925ab.firebaseapp.com',
    storageBucket: 'simpleca-925ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQuhzovT9bopSquos8m46_D7C-QBQ3N7g',
    appId: '1:902733428361:android:c2293b3204a184558ab858',
    messagingSenderId: '902733428361',
    projectId: 'simpleca-925ab',
    storageBucket: 'simpleca-925ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfFrsMAXQrcD4zrd1tTmZ82eRR-DFikBU',
    appId: '1:902733428361:ios:6900e1f6401a416c8ab858',
    messagingSenderId: '902733428361',
    projectId: 'simpleca-925ab',
    storageBucket: 'simpleca-925ab.firebasestorage.app',
    iosBundleId: 'com.example.queueaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfFrsMAXQrcD4zrd1tTmZ82eRR-DFikBU',
    appId: '1:902733428361:ios:6900e1f6401a416c8ab858',
    messagingSenderId: '902733428361',
    projectId: 'simpleca-925ab',
    storageBucket: 'simpleca-925ab.firebasestorage.app',
    iosBundleId: 'com.example.queueaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW16KCmgWhL9xXjxFpfIl61D4-ia2Lwcs',
    appId: '1:902733428361:web:cc220bc00a72edfc8ab858',
    messagingSenderId: '902733428361',
    projectId: 'simpleca-925ab',
    authDomain: 'simpleca-925ab.firebaseapp.com',
    storageBucket: 'simpleca-925ab.firebasestorage.app',
  );
}
